apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    build.appstudio.redhat.com/expires-on: "2025-05-31T00:00:00Z"
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
  name: summary
spec:
  description: >-
    Summary Pipeline Task. Prints PipelineRun information, removes image repository secret used by the PipelineRun.
  params:
    - name: pipelinerun-name
      description: pipeline-run to annotate
    - name: git-url
      description: Git URL
    - name: image-url
      description: Image URL
    - name: build-task-status
      description: State of build task in pipelineRun
      # Default Succeeded for backward compatibility
      default: Succeeded
  steps:
    - name: appstudio-summary
      image: registry.access.redhat.com/ubi9/ubi-minimal:9.6-1752069876@sha256:11db23b63f9476e721f8d0b8a2de5c858571f76d5a0dae2ec28adf08cbaf3652
      # per https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
      # the cluster will set imagePullPolicy to IfNotPresent
      env:
        - name: GIT_URL
          value: $(params.git-url)
        - name: IMAGE_URL
          value: $(params.image-url)
        - name: PIPELINERUN_NAME
          value: $(params.pipelinerun-name)
        - name: BUILD_TASK_STATUS
          value: $(params.build-task-status)
      script: |
        #!/usr/bin/env bash
        echo
        echo "Build Summary:"
        echo
        echo "Build repository: $GIT_URL"
        if [ "$BUILD_TASK_STATUS" == "Succeeded" ]; then
          echo "Generated Image is in : $IMAGE_URL"
        fi
        echo
        echo End Summary
